from os import environ

IMGUR_CLIENT_ID = environ['IMGUR_CLIENT_ID']
IMGUR_CLIENT_SECRET = environ['IMGUR_CLIENT_SECRET']
GFYCAT_CLIENT_ID = environ['GFYCAT_CLIENT_ID']
GFYCAT_CLIENT_SECRET = environ['GFYCAT_CLIENT_SECRET']
AIRBRAKE_API_KEY = environ['AIRBRAKE_API_KEY']
AIRBRAKE_PROJECT_ID = environ['AIRBRAKE_PROJECT_ID']
REDDIT_CLIENT_ID = environ['REDDIT_CLIENT_ID']
REDDIT_CLIENT_SECRET = environ['REDDIT_CLIENT_SECRET']
REDDIT_CLIENT_ID_TESTING = environ['REDDIT_CLIENT_ID_TESTING']
REDDIT_CLIENT_SECRET_TESTING = environ['REDDIT_CLIENT_SECRET_TESTING']
REDDIT_USERNAME = environ['REDDIT_USERNAME']
REDDIT_USERNAME_TESTING = environ['REDDIT_USERNAME_TESTING']
REDDIT_PASSWORD = environ['REDDIT_PASSWORD']
EMAIL = environ['EMAIL']
KEEN_PROJECT_ID = environ['KEEN_PROJECT_ID']
KEEN_WRITE_KEY = environ['KEEN_WRITE_KEY']
REDIS_URL = environ['REDIS_URL']

SLEEP_TIME = 5
MARK_READ = True
