version: '3'

services:
  gifendore:
    build: .
    command: python -u main.py -D -M
    # command: python -u main.py production -M
    container_name: gifendore
    restart: always
    env_file:
      - .env
    networks:
      gifendore_net:
        ipv4_address: 10.0.0.2

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo/data:/data/db
    restart: always
    networks:
      gifendore_net:
        ipv4_address: 10.0.0.3

  redisdb:
    image: redis:latest
    container_name: redisdb
    restart: always
    networks:
      gifendore_net:
        ipv4_address: 10.0.0.4
networks:
  gifendore_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29